c	: "gcc"
cxx	: "g++"
cu      : "nvcc"
f77     : "gfortran"
f90     : "gfortran"
f95     : "gfortran"
f03     : "gfortran"
f08     : "gfortran"

cflags    : ""
openmp    : ""
tbb       : ""
accl      : ""
strict	  : "-Wall -Werror -pedantic"

