image: "python:3.6"

before_script:
- pip3 install tox

variables:
    GIT_CLEAN_FLAGS: -fddx -e .coverage

.scope: &scope
    tags:
    - docker
    only:
    - master
    - merge_requests
    - web

stages:
- warmup
- tests
- misc
- lint

flake8:
    <<: *scope
    stage: lint
    script:
    - tox -e py-lint
yaml:
    <<: *scope
    stage: lint
    script:
    - tox -e yaml-lint

cli:
    <<: *scope
    stage: tests
    script:
    - tox -- cli

backend:
    <<: *scope
    stage: tests
    script:
    - tox -- backend

helpers:
    <<: *scope
    stage: tests
    script:
    - tox -- helpers

      #converter:
      #    <<: *scope
      #    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
      #    stage: tests
      #    script:
      #    - pip install -e .
      #    - pytest ./tests/pcvs/converter

documentation:
    <<: *scope
    stage: misc
    script:
    - tox -e docs

imports:
    <<: *scope
    stage: misc
    allow_failure: true
    script:
    - tox -e order_imports
