image: "python:3.7"

before_script:
- python --version
- pip install flake8 mypy pytest pytest-cov

.scope: &scope
    tags:
    - docker
    only:
    - master
    - merge_requests
    - web

stages:
- install
- lint
- unit_tests
- coverage


flake:
    <<: *scope
    stage: lint
    allow_failure: true
    script:
    - flake8 ./pcvs/

mypy:
    <<: *scope
    stage: lint
    allow_failure: true
    script:
    - python -m mypy ./pcvs/

main:
    <<: *scope
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: unit_tests
    script:
    - pip install -e .
    - pytest ./tests/pcvs/cli

converter:
    <<: *scope
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: unit_tests
    script:
    - pip install -e .
    - pytest ./tests/pcvs/converter

helpers:
    <<: *scope
    stage: unit_tests
    script:
    - pip install -e .
    - pytest ./tests/pcvs/helpers

full_nr:
    <<: *scope
    stage: coverage
    script:
    - pip install -e .
    - pytest ./tests/pcvs --cov=pcvs


pip:
    <<: *scope
    stage: install
    script:
    - pip3 install wheel
    - python3 setup.py bdist_wheel
    - pip3 install dist/*.whl
    - pcvs --version

from_sources:
    <<: *scope
    stage: install
    script:
    - mkdir dist_sources
    - python3 setup.py sdist --formats=gztar
    - tar xf dist/pcvs-*.tar.gz -C $PWD/dist_sources
    - python3 $PWD/dist_sources/*/setup.py install
    - pcvs --version

    
