image: "python:3.7"

before_script:
- python --version
- pip install flake8 mypy pytest pytest-cov

.scope: &scope
    tags:
    - docker
    only:
    - master
    - merge_requests
    - web

stages:
- lint
- install
- cli_test
- unit_test

flake:
    <<: *scope
    stage: lint
    allow_failure: true
    script:
    - flake8 ./pcvsrt/

mypy:
    <<: *scope
    stage: lint
    allow_failure: true
    script:
    - python -m mypy ./pcvsrt/

cli_config:
    <<: *scope
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: cli_test
    script:
    - pip install .
    - pytest ./tests/pcvsrt/cli --cov=pcvsrt --cov-report=xml -k _config

cli_profile:
    <<: *scope
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: cli_test
    script:
    - pip install .
    - pytest ./tests/pcvsrt/cli --cov=pcvsrt --cov-report=xml -k _profile

cli_run:
    <<: *scope
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: cli_test
    script:
    - pip install .
    - pytest ./tests/pcvsrt/cli --cov=pcvsrt --cov-report=xml -k _run

tbw:
    <<: *scope
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    stage: unit_test
    script:
    - exit 1