image: 'python:3.6'

before_script:
- pip3 install -rrequirements-dev.txt

variables:
    GIT_CLEAN_FLAGS: -fddx -e .coverage

.scope: &scope
    tags:
    - docker
    only:
    - master
    - merge_requests
    - web

stages:
- Installation
- Pytest
- Formatting
- Documentation
- Static Analysis

io-yaml:
    <<: *scope
    stage: Formatting
    script:
    - tox -e lint-yaml

global-lint:
    <<: *scope
    stage: Static Analysis
    allow_failure: true
    script:
    - tox -e lint-generic

types:
    <<: *scope
    stage: Static Analysis
    allow_failure: true
    script:
    - tox -e lint-type

build_doc:
    <<: *scope
    stage: Documentation
    script:
    - tox -e docs

imports:
    <<: *scope
    stage: Static Analysis
    script:
    - tox -e lint-import

.pytest:
    <<: *scope
    stage: Pytest
    script:
    - pip3 install .
    - coverage run --source=./pcvs -m pytest ./tests/pcvs
    - coverage report

setuptools:
    <<: *scope
    stage: Installation
    script:
    - python3 setup.py build
    - python3 setup.py install
    - pcvs

pip:
    <<: *scope
    stage: Installation
    script:
    - pip3 install .
    - pcvs

Python3.6:
    extends: .pytest
    image: "python:3.6"
Python3.7:
    extends: .pytest
    image: "python:3.7"
Python3.8:
    extends: .pytest
    image: "python:3.8"

