image: "python:3.6"

before_script:
- pip3 install tox

variables:
    GIT_CLEAN_FLAGS: -fddx -e .coverage

.scope: &scope
    tags:
    - docker
    only:
    - master
    - merge_requests
    - web

stages:
- warmup
- tests
- lint
- misc

clean:
    <<: *scope
    stage: warmup
    allow_failure: true
    script:
    - tox -e clean

flake8:
    <<: *scope
    stage: lint
    allow_failure: true
    script:
    - tox -e lint
yaml:
    <<: *scope
    stage: lint
    allow_failure: true
    script:
    - tox -e yaml-lint

cli:
    <<: *scope
    stage: tests
    script:
    - tox -e tests cli

backend:
    <<: *scope
    stage: tests
    script:
    - tox -e tests backend

helpers:
    <<: *scope
    stage: tests
    script:
    - tox -e tests helpers

      #converter:
      #    <<: *scope
      #    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
      #    stage: tests
      #    script:
      #    - pip install -e .
      #    - pytest ./tests/pcvs/converter

coverage:
    <<: *scope
    stage: misc
    script:
    - tox -e report

documentation:
    <<: *scope
    stage: misc
    script:
    - tox -e docs

imports:
    <<: *scope
    stage: misc
    allow_failure: true
    script:
    - tox -e imports