#define which compiler config will be loaded (/build_scripts/configuration/compilers/*.yml)
compiler-target: "default"

#define which runtime config will be loaded (/build_scripts/configuration/runtimes/*.yml)
runtime-target: "default"

#define the default group to include into combinatory system
group-target: "default"

# list of iterators for this run. A missing line will deactivate an iterator
iterators:
    n_node : ["1:2:*2"]
    n_proc : ["1:4:*2"]
    n_mpi  : ["1:8:*2"]
    n_omp  : ["1:8:*2"]
    n_core : ["1:4:*2"]
    sched  : ["pthread", "ethread_mxn"]
    net    : ["ib", "tcp", "shmem"]

# just the naming convention (in test names) for the above iterators. The key will
# be prepended to the iterator value for each test.
naming:
    n_node : "N"
    n_proc : "P"
    n_mpi  : "np"
    n_omp  : "o"
    n_core : "c"
    sched  : ""
    net    : ""

# cluster parameters for the current run. Combinations will be affected by these parameters
cluster:
    max_nodes          : 1
    max_cores_per_node : 4
    args               : ""

# generic options to affect the validation. To keep it simple, most of these parameters
# can only be altered through this configuration (no command-line options overriding)
validation:
    # returns non-zero code if at least one test failed
    expect-success : 0            
    support_model  : "supported"
    # validation stdout will be logged into build/output.log
    tee            : 1            
    # number of concurrent JCHRONOSS workers
    workers        : 10           
    # Scheduling policy  (JCHRONOSS)
    sched_policy   : 0            
    # allocation wrapper (JCHRONOSS)
    run_wrapper    : ""           
    # compilation-specific allocation wrapper (JCHRONOSS)
    compil_wrapper : ""           
    # should not make an resource allocation if expected time does not reach this value
    worker_mintime : 0            
    # set a timer to avoid job manager autokill if a resource allocatio reaches this value
    worker_maxtime : 3000         
    # if time not specified per test, use this one by default
    job_meantime   : 50           

