##################################################
# GLOBAL GROUPS, WHICH CAN BE USED DIRECTLY
# IN THE VALIDATION BY REFERENCING THE OBJECT
# WITH ONE OF THE FOLLOWING LABEL:
# ################################################

pcvst_grp_mpi:     &GRPMPI
        n_omp: ~
        n_mpi: [2, 4, 8]

pcvst_grp_omp:     &GRPOMP
        n_node: ~
        n_proc: ~
        n_mpi: ~
        net: ~

pcvst_grp_hybrid:  &GRPHYB

pcvst_grp_app:     &GRPAPP

pcvst_grp_accl:    &GRPACCL

pcvst_grp_serial:  &GRPSERIAL
        n_node: [1]
        n_proc: [1]
        n_mpi: [1]
        n_omp: [1]
        net: ~

##################################################
# END OF GROUP DEFINITION
##################################################

