cmd   : ""
args  : ""
module: "Default"
timeout_prefix: ""

n_node:
        key             : ""
        usage           : ""

n_proc:
        key             : ""
        usage           : ""

n_mpi:
        key             : ""
        usage           : ""

n_omp:
        key             : ""
        usage           : ""

n_core:
        key             : ""
        usage           : ""

sched:
        key             : ""
        usage           : ""

        ethread_val     : ""
        pthread_val     : ""
        ethread_mxn_val : ""

net:
        key         : ""
        usage       : ""

        ib_val      : ""
        tcp_val     : ""
        shmem_val   : ""
        portals_val : ""

