#define which compiler config will be loaded (/build_scripts/configuration/compilers/*.yml)
compiler-target: "default"

#define which runtime config will be loaded (/build_scripts/configuration/runtimes/*.yml)
runtime-target: "default"

#define the default group to include into combinatory system
group-target: "default"

# list of iterators for this run. A missing line will deactivate an iterator
iterators:
    n_node : ~
    n_proc : ~
    n_mpi  : ~
    n_omp  : ~
    n_core : ~
    sched  : ~
    net    : ~

# just the naming convention (in test names) for the above iterators. The key will
# be prepended to the iterator value for each test.
naming:
    n_node : "N"
    n_proc : "P"
    n_mpi  : "np"
    n_omp  : "o"
    n_core : "c"
    sched  : ""
    net    : ""

# cluster parameters for the current run. Combinations will be affected by these parameters
cluster:
    max_nodes          : 1
    max_cores_per_node : 4
    launcher           : ""
    args               : ""

# generic options to affect the validation. To keep it simple, most of these parameters
# can only be altered through this configuration (no command-line options overriding)
validation:
    # job timeout (by default, it is recommended to set it to avoid tests blocking validation completion)
    timeout        : 1000
    # returns non-zero code if at least one test failed
    expect-success : 0            
    # validation stdout will be logged into build/output.log
    tee            : 1            
    # number of concurrent JCHRONOSS workers
    workers        : 1 
    # Scheduling policy  (JCHRONOSS)
    sched_policy   : 0
    # allocation wrapper (JCHRONOSS)
    run_wrapper    : "default"           
    # compilation-specific allocation wrapper (JCHRONOSS)
    compil_wrapper : "default"           
    # should not make an resource allocation if expected time does not reach this value
    worker_mintime : 0            
    # set a timer to avoid job manager autokill if a resource allocatio reaches this value
    worker_maxtime : 30000
    # if time not specified per test, use this one by default
    job_meantime   : 50           
    # level of resources considered by JCHRONOSS (need to be an iterator name
    resource_level : "n_node"
    # file logging level: (0) None, (1) only Failed, (2) only Success and (3) everything
    # This is different that what it displayed in the terminal (see verbose option)
    logging        : 0
    # verbosity level (steering what is written on standard output)
    verbose        : 0
    # output formats (from JCHRONOSS°
    #formats        : [ "junit" ]

