#!/usr/bin/env python3

import click

@click.group()
@click.option("--test/--no-test", "-t/-T", "t", default=False)
def cli(test):
    click.echo("Hi from test: {}".format(test))
    

@cli.command()
@click.option("--other", default=2)
def sub(other):
    click.echo("Hi {}".format(other))

if __name__ == '__main__':
    

    pass