---
cc: {program: icc, variants: &var {openmp: {args: ["-fopenmp"]}}}
cxx: {program: icpc, variants: *var}
f77: {program: ifort, variants: *var}
f90: {program: ifort, variants: *var}
f08: {program: ifort, variants: *var}
fc: {program: ifort, variants: *var}