---
# Please here defines nodes like regular TEs
# None of these templates will be unrolled
# first-level keys can then be used in `group' field
GRPMPI:
  run:
    iterate:
      n_omp:
        values: null
GRPOMP:
  run:
    iterate:
      n_mpi:
        values: null
      n_node:
        values: null
GRPSERIAL:
  run:
    iterate:
      n_core:
        values: null
      n_mpi:
        values: null
      n_node:
        values: null
      n_omp:
        values: null