---
# program path to run any program (can be a name if in $PATH)
program: ''

# Declaration of criterion
# Here is set any element to describe what an criterion iterator does
# A criterion is small component a test is relying on to be validated
# For instance, an MPI program has the following components:
# - number of nodes to be executed on
# - number of MPI ranks
# - number of cores allocated for each MPI rank
# - Type of network to enable inter process communication
# A single test is a combination of one single value picked up from
# these components.
criterions:
    void:
        option: ''

